### PR TITLE
`visualizer` example

### PR DESCRIPTION
**Pull request by 223230**

### CODE REVIEW

**Comment by magnetophon** [comment]
Thank you soooo much!!!

**Comment by magnetophon** [comment]
When I try to run the example, it doesn't seem to find the font:
```
[ERROR] thread 'unnamed' panicked at 'Failed to find font: Query { families: [Name("Noto Sans"), SansSerif], weight: Weight(300), stretch: Normal, style: Normal }': /home/bart/.cargo/git/checkouts/vizia-629668219022e428/0a4af19/crates/vizia_core/src/text/cosmic.rs:143
```

**Comment by 223230** [comment]
Well that's weird :/ Might be because the call to `register_noto_sans_light()` is missing from the editor `create()` function. I'm gonna quickly check if that fixes it on Linux!

**Comment by magnetophon** [comment]
Yes, that fixes it!  :)

**Comment by 223230** [comment]
Nice! Was it just that one function call or did you do anything else? And could you file a PR with your changes?

**Comment by magnetophon** [comment]
Here you go: https://github.com/223230/cyma/pull/35  :)

**Pull request merged**
